name: Go Build
run-name: Building a Go program
on:
  push:
    branches: ["Aula_2"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare DB
        uses: ./.github/actions/prepare-db

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.18.1"

      - name: Test
        run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: go build -v main.go
