name: Go Build
run-name: Building a Go program
on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-latest"]
        go-version: ["1.16", "1.18", "1.20", "1.22"]
    env:
      DB_HOST: localhost
      DB_PORT: 5432

      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare DB
        uses: ./.github/actions/prepare-db

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.16

      - name: Build
        run: go build -v main.go

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: program
          path: main

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit

