name: Load Test

on:
  workflow_call:
  
jobs:
  ecs:
    runs-on: ubuntu-latest
    environment: Curso_CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - run: git clone https://github.com/JefersonBatista/Infra_CI

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - run: terraform -chdir=Infra_CI/env/Homolog init

      - name: Destroy test infrastructure
        run: terraform -chdir=Infra_CI/env/Homolog destroy -auto-approve
  
