name: Docker Build
run-name: Building a Docker Container
on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Curso_CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
