name: Docker Build
run-name: Building a Docker Container
on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Curso_CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jefersonbatista/curso_ci:${{ github.ref_name }}
