name: Deploy in EC2

on:
  workflow_dispatch:
  
jobs:
  ec2:
    runs-on: ubuntu-latest
    environment: Curso_CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: program

      - name: Deploy to Staging Server
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}
          EXCLUDE: "postgres-data"

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_USER=${{ secrets.DB_USER }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_PORT=${{ secrets.DB_PORT }}
            export PORT=8000
            chmod +x main
            nohup ./main > nohup.out 2> nohup.err < /dev/null &
