name: Kubernetes

on:
  workflow_call:
  
jobs:
  eks:
    runs-on: ubuntu-latest
    environment: Curso_CI
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: git clone https://github.com/JefersonBatista/Infra_CI_Kubernetes

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
  
      - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog init

      - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog apply -auto-approve
