name: Load Test

on:
  workflow_call:
  
jobs:
  ecs:
    runs-on: ubuntu-latest
    environment: Curso_CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: git clone https://github.com/JefersonBatista/Infra_CI

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - run: terraform --chdir=Infra_CI/env/Homolog init

      - run: terraform --chdir=Infra_CI/env/Homolog destroy -auto-aprove

      - run: terraform --chdir=Infra_CI/env/Homolog apply -auto-aprove

      - run: echo "${terraform --chdir=Infra_CI/env/Homolog output -raw IP_alb}"

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Locust
        uses: insightsengineering/pip-action@v2
        with:
          packages: |
            locust
  
